### ISSUE TITLE
Update External Projects

### ISSUE THREAD

**Issue by cdarwin** [performanceci/performanceci-core#47]
As a perfci user, I should be able to update a project configuration through the UI.

## Acceptance Criteria

* UI element for project configuration
* project configuration page displays current config as editable text
* save UI element updates project configuration

**Comment by akira** [comment]
@cdarwin any thoughts on how to present this in the UI?  Maybe something like [TravisCI](https://travis-ci.org/akira/exq) - with a tabbed navigation and/or settings link?

**Comment by cdarwin** [comment]
yeah, that would be nice. Initially, would it be easier to reuse the UI associated with creating an external project? That just presents an example config for the user to update according to their needs.

Eventually, we may want to restrict the config options to just those that we recognize internally. Something like adding an external project provides required fields for setting a base URL and port as well as optional fields for concurrency and duration (maybe greyed out defaults in the text fields here?). This then provides a new set of fields for adding and configuring endpoints associate with the project, where we require at least one endpoint configured.

Do you get the idea? I'll try to draw something up to clarify.

**Comment by akira** [comment]
Yeah, we can reuse the form for edit.  I was more talking about the link to the edit view and how to present that. 

I like being able to edit things as JSON vs having to create forms, but I can see others may want to edit via a more constrained view.  Validating the options to ones that are valid sounds good as well.
